from enum import IntEnum, auto


class InputCommands(IntEnum):
    X_CW = auto(),
    X_CCW = auto(),
    Y_UP = auto(),
    Y_DOWN = auto(),
    Z_UP = auto(),
    Z_DOWN = auto(),
    A_CW = auto(),
    A_CCW = auto(),
    B_UP = auto(),
    B_DOWN = auto(),
    C_CW = auto(),
    C_CCW = auto(),
    AXIS_RELEASE = auto(),
    END_EFF_CLOSE = auto(),
    END_EFF_OPEN = auto(),
    SPEED_SLOW = auto(),
    SPEED_MEDIUM = auto(),
    SPEED_HIGH = auto(),
    AXIS_STOP = auto(),
    REC_TOGGLE = auto(),
    RUN_CALIBRATION = auto(),
    MACRO_1 = auto(),
    MACRO_2 = auto(),
    MACRO_3 = auto(),
    MACRO_4 = auto(),
    MACRO_5 = auto(),
    MACRO_6 = auto(),
    MACRO_7 = auto(),
    MACRO_8 = auto(),
    MACRO_9 = auto(),
    REQUEST_ROBOT_STATUS = auto(),
    SOFT_RESET = auto(),
    SEND_JOG_STOP = auto(),
    RETURN_TO_ORIGIN = auto(),
    RETURN_TO_NEUTRAL = auto(),
    ZERO_AXES = auto(),
    TOGGLE_KEY_LOCK = auto(),
    STORAGE_CONFIGURATION = auto()
    CLAW_DEMO = auto(),
    HARD_ZERO = auto()

